server:
  port: your_choice_port_number
  servlet:
    context-path: /api/v1

---

spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 50MB

  application:
    name: appointment-scheduler

  datasource:
    url: jdbc:postgresql://localhost:5432/appointment_dev
    username: your_db_username
    password: your_db_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: your_email@gmail.com
    password: your_email_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 60000
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1
          max-wait: 5000

jwt:
  secret: your_jwt_secret_key
  expiration: 86400000
  refresh-expiration: 604800000

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

swagger:
  server-url: https://localhost:8085/api/v1

cloudinary:
  cloud_name: your_cloud_name
  api_key: your_cloudinary_api_key
  api_secret: your_cloudinary_api_secret
