package com.cw.scheduler.advice;

public enum ErrorCode {
    USER_NOT_FOUND, INVALID_CREDENTIALS, EMAIL_ALREADY_EXISTS, OTP_EXPIRED, INVALID_OTP, APPOINTMENT_NOT_FOUND, SCHEDULE_CONFLICT, PROVIDER_UNAVAILABLE, EMAIL_SEND_FAILED, BAD_REQUEST, ACCESS_DENIED, RESOURCE_NOT_FOUND, VALIDATION_FAILED, INVALID_TOKEN, TOKEN_EXPIRED, TOO_MANY_REQUESTS, ROLE_NOT_FOUND, DUPLICATE_RESOURCE, OUTSIDE_WORKING_HOURS, BAD_CREDENTIALS, MULTIPART_ERROR, RATE_LIMIT_EXCEEDED, SOMETHING_WENT_WRONG
}
